apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    app: mini2-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini2-transaction
  template:
    metadata:
      labels:
        app: mini2-transaction
    spec:
      containers:
        - name: mini2-transaction
          image: subo8/mini2-transaction:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: mini2-transaction
    type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084