apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: mini2-payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini2-payment
  template:
    metadata:
      labels:
        app: mini2-payment
    spec:
      containers:
        - name: mini2-payment
          image: subo8/mini2-payment:latest
          ports:
            - containerPort: 8050
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: mini2-payment
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050