apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-service
  labels:
    app: mini2-shipment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini2-shipment
  template:
    metadata:
      labels:
        app: mini2-shipment
    spec:
      containers:
        - name: mini2-shipment
          image: subo8/mini2-shipment:latest
          ports:
            - containerPort: 8060
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: shipment-service
spec:
  selector:
    app: mini2-shipment
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060