apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-configmap
data:
  SPRING_PROFILES_ACTIVE: dev
#  SPRING_CONFIG_IMPORT: configserver:http://configserver-service:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/